# Importing libraries and data needed

In [25]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import random
import os
import keras

Using TensorFlow backend.


# Setting up datetime and logdir for tensorboard 

In [2]:
from datetime import datetime
from datetime import timezone

def utc_to_local(utc_dt):
    return utc_dt.replace(tzinfo=timezone.utc).astimezone(tz=timedelta(hours=9))

# Data loading, preprocessing

In [3]:
df = pd.read_csv("number_165688.csv", encoding="ISO-8859-1") ## 한글 어떻게 인식?

In [4]:
print(df.head(5))

   YYYYMM  TPLMA    HAUS    VSTELLE      ANLAGE      VKONT  I_ABRMENGE  \
0  201401   1027  165688  501704310  6100861465  109045365    340.3862   
1  201401   1027  165688  501704325  6100861446  108944373    218.6058   
2  201401   1027  165688  501704341  6100861343  108944372     28.9478   
3  201401   1027  165688  501704486  6100861323  300832851    103.8128   
4  201401   1027  165688  501704506  6100861308  108944433    125.7732   

   USE_DATE_FR  USE_DATE_TO  USE_DAYS INJUNG_GOJI   AGE SEX  FST_SPLY_DAT  \
0     20131223     20140122        31           N  58.0   M      19891106   
1     20131223     20140122        31           N  75.0   M      19891108   
2     20131223     20140122        31           N  73.0   F      19891102   
3     20131223     20140122        31           N  56.0   M      19900404   
4     20131223     20140122        31           N  46.0   F      19891102   

  AKLASSE  ANLART   ADRNR   MC_CITY1 MC_STREET  METER_GRD  
0    LRH1     125  449329  ÀÎõ 

In [5]:
##

df.drop(columns=['TPLMA','HAUS','VSTELLE','VKONT','USE_DATE_FR','USE_DATE_TO','USE_DAYS','INJUNG_GOJI','AGE','SEX','FST_SPLY_DAT','AKLASSE','ANLART','ADRNR','MC_CITY1','MC_STREET','METER_GRD'])

YYYYMM      ANLAGE  I_ABRMENGE
0     201401  6100861465    340.3862
1     201401  6100861446    218.6058
2     201401  6100861343     28.9478
3     201401  6100861323    103.8128
4     201401  6100861308    125.7732
5     201401  6100861282    162.7066
6     201401  6100861257    268.5158
7     201401  6100861237     27.9496
8     201401  6100861223      0.9982
9     201401  6100861207    118.7858
10    201401  6100861179    156.7174
11    201401  6100861159    123.7768
12    201401  6100861143     84.8470
13    201401  6100861122    159.7120
14    201401  6100861104     70.8722
15    201401  6100861084     92.8326
16    201401  6100861040    154.7210
17    201401  6100860987     29.9460
18    201401  6100860954    254.5410
19    201401  6100860919     48.9118
20    201401  6100860899    123.7768
21    201401  6100860883     88.8398
22    201401  6100860868    118.7858
23    201401  6100860838    229.5860
24    201401  6100860809      0.0000
25    201401  6100860787    144.7390
26    201401  6100860768     81.8524
27    201401  6100860756    199.6400
28    201401  6100860734    189.6580
29    201401  6100860715    228.5878
...      ...         ...         ...
3521  201812  6100860715    203.6736
3522  201812  6100860690    138.7776
3523  201812  6100860676     69.8880
3524  201812  6100860645     21.9648
3525  201812  6100860617     22.9632
3526  201812  6100860596    111.8208
3527  201812  6100860581     68.8896
3528  201812  6100860563    155.7504
3529  201812  6100860531    102.8352
3530  201812  6100860507    132.7872
3531  201812  6100860485     34.9440
3532  201812  6100860464     91.8528
3533  201812  6100860445    205.6704
3534  201812  6100860429    152.7552
3535  201812  6100860394    200.6784
3536  201812  6100860375    100.8384
3537  201812  6100860358     15.9744
3538  201812  6100860340    101.8368
3539  201812  6100860311      3.9936
3540  201812  6100860296      0.9984
3541  201812  6100860278    176.7168
3542  201812  6100860252     63.8976
3543  201812  6100860228    197.6832
3544  201812  6100860208     41.9328
3545  201812  6100860187    239.6160
3546  201812  6100860166     19.9680
3547  201812  6100860147    207.6672
3548  201812  6100860126    137.7792
3549  201812  6100860091     27.9552
3550  201812  6100860071     92.8512

[3551 rows x 3 columns]

In [6]:
df2 = df.pivot(index='YYYYMM', columns='ANLAGE', values='I_ABRMENGE')

In [7]:
print(df2.head(5))

ANLAGE  6100860071  6100860091  6100860126  6100860147  6100860166  \
YYYYMM                                                               
201401    110.8002     68.8758     13.9748    155.7192     52.9046   
201402    127.7696     79.8560     11.9784    140.7462     44.9190   
201403     75.8809     28.9547     24.9613     23.9625     34.9454   
201404     54.9175      9.9850     10.9835      9.9850     16.9745   
201405     50.9235      8.9865      7.9880      5.9910     11.9820   

ANLAGE  6100860187  6100860208  6100860228  6100860252  6100860278  ...  \
YYYYMM                                                              ...   
201401    253.5428     59.8920    191.6544     85.8452    149.7300  ...   
201402    284.4870     56.8974    199.6400     69.8740    162.7066  ...   
201403    178.7225     17.9718    156.7564     55.9133    113.8233  ...   
201404    152.7705     35.9460    110.8335     11.9820     66.8995  ...   
201405    110.8335     14.9775     62.9055      8.9865     

In [8]:
print(df2)

VSTELLE    501704310    501704325    501704341    501704486    501704506  \
YYYYMM                                                                     
201401   109045365.0  108944373.0  108944372.0  300832851.0  108944433.0   
201402   109045365.0  108944373.0  108944372.0  300832851.0  108944433.0   
201403   109045365.0  108944373.0  108944372.0  300832851.0  108944433.0   
201404   301772442.0  108944373.0  108944372.0  300832851.0  108944433.0   
201405   301772442.0  108944373.0  108944372.0  300832851.0  108944433.0   
201406   301772442.0  108944373.0  108944372.0  300832851.0  108944433.0   
201407   301772442.0  108944373.0  108944372.0  300832851.0  108944433.0   
201408   301772442.0  108944373.0  108944372.0  300832851.0  108944433.0   
201409   301772442.0  108944373.0  108944372.0  300832851.0  108944433.0   
201410   301772442.0  108944373.0  108944372.0  300832851.0  108944433.0   
201411   301772442.0  108944373.0  108944372.0  300832851.0  108944433.0   
201412   301

# LSTM Model

In [8]:
timesteps = 12
data_dim = 60
output_dim=60

In [9]:
xy = np.asarray(df2)

In [10]:
xy

array([[110.8002,  68.8758,  13.9748, ...,  28.9478, 218.6058, 340.3862],
       [127.7696,  79.856 ,  11.9784, ...,  12.9766, 225.5932, 229.586 ],
       [ 75.8809,  28.9547,  24.9613, ...,  24.9613, 181.7177, 152.8263],
       ...,
       [ 55.9104,   7.9872,   6.9888, ...,   8.9856,   4.992 ,  35.9424],
       [ 70.8864,   8.9856,  33.9456, ...,  12.9792,  11.9808,  35.9424],
       [ 92.8512,  27.9552, 137.7792, ...,  34.944 ,  15.9744,  79.872 ]])

In [11]:
train_size= int(len(xy)*0.7)
train_set = xy[:train_size]
test_set = xy[train_size-timesteps:]

In [12]:
print(test_set)

[[ 29.943    4.9905   3.9924 ...  10.9791   8.9829   6.9867]
 [ 20.9601  11.9772   2.9943 ...  10.9791   3.9924   5.9886]
 [ 26.9487  10.9791   3.9924 ...  12.9753   5.9886   6.9867]
 ...
 [ 55.9104   7.9872   6.9888 ...   8.9856   4.992   35.9424]
 [ 70.8864   8.9856  33.9456 ...  12.9792  11.9808  35.9424]
 [ 92.8512  27.9552 137.7792 ...  34.944   15.9744  79.872 ]]


In [13]:
def build_dataset(time_series, timesteps):
    dataX = []
    dataY = []
    for i in range(0,len(time_series) - timesteps):
        _x = time_series[i:i + timesteps, :]
        _y = time_series[i + timesteps, :]
        print(_x, "->", _y)
        dataX.append(_x)
        dataY.append(_y)
    return dataX, dataY

In [14]:
trainX, trainY = build_dataset(train_set, timesteps)
testX, testY = build_dataset(test_set, timesteps)

[[110.8002  68.8758  13.9748 155.7192  52.9046 253.5428  59.892  191.6544
   85.8452 149.73     6.9874  22.9586 139.748   55.8992 220.6022 316.4294
  170.6922 223.5968 107.8056  45.9172 121.7804 244.559   24.955  112.7966
   70.8722 113.7948  76.8614 100.8182  78.8578 228.5878 189.658  199.64
   81.8524 144.739    0.     229.586  118.7858  88.8398 123.7768  48.9118
       nan 254.541   29.946  154.721   92.8326  70.8722 159.712   84.847
  123.7768 156.7174 118.7858   0.9982  27.9496 268.5158 162.7066 125.7732
  103.8128  28.9478 218.6058 340.3862]
 [127.7696  79.856   11.9784 140.7462  44.919  284.487   56.8974 199.64
   69.874  162.7066  17.9676  33.9388 312.4366  78.8578 209.622  444.199
  159.712  193.6508 153.7228  44.919  122.7786 165.7012  18.9658  95.8272
   66.8794 123.7768  82.8506  89.838  116.7894 229.586  196.6454 179.676
   69.874   83.8488  99.82   209.622  116.7894  91.8344  95.8272 103.8128
       nan 229.586   22.9586 157.7156 256.5374  65.8812 100.8182  56.8974
  120.

   95.838   13.9768  80.8632  69.882 ]] -> [ 57.9072  14.976   38.9376 111.8208   9.984  167.7312  32.9472 132.7872
  30.9504  72.8832   1.9968 107.8272  48.9216   3.9936 129.792  186.7008
  69.888  144.768   35.9424  39.936   55.9104  99.84    15.9744  39.936
  99.84    25.9584  16.9728  47.9232  25.9584  17.9712  82.8672  67.8912
  34.944  138.7776  25.9584 109.824   95.8464  91.8528   0.      15.9744
  60.9024 196.6848  39.936   90.8544 108.8256  49.92     0.      70.8864
  26.9568  50.9184  32.9472      nan 189.696  115.8144  99.84   119.808
  67.8912  15.9744  80.8704  61.9008]
[[ 47.904    2.994   10.978    2.994    9.98    59.88    28.942   52.894
   13.972   41.916    0.998   57.884   23.952    1.996   89.82    92.814
   25.948   87.824   39.92    25.948   31.936   65.868   20.958    0.
    0.      60.878   25.948   20.958    5.988   22.954   57.884   38.922
   22.954    8.982   15.968   28.942    6.986   38.922   34.93     9.98
   42.914  119.76    13.972   53.892   38.922   5

In [23]:
# input place holders
X = tf.placeholder(tf.float32, [None, 12, 60])
Y = tf.placeholder(tf.float32, [None, 60])

In [24]:
## Resetting Graph
tf.reset_default_graph()

In [19]:
# build a LSTM network

hidden_dim = 10
learning_rate = 0.01
iterations = 500

basic_cell = tf.nn.rnn_cell.LSTMCell(name='basic_lstm_cell', num_units=hidden_dim, state_is_tuple=True) ## state_is_tuple?

outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32) 
## Cell에 입력 X, 입력 데이터형태 제시,
## (matmul() 등을 실행하여 계속 가중치 W, 편향 b들을 업데이트)
## static_rnn 함수의 결과값은 두 가지 객체임. 1. 각 타임스텝에서의 출력 텐서를 담고 있는 파이썬 리스트 2. 네트워크의 최종 상태 텐서

Y_pred = tf.contrib.layers.fully_connected(
    outputs, output_dim, activation_fn=None)  # We use the last cell's output

ValueError: Tensor("rnn/Const:0", shape=(1,), dtype=int32) must be from the same graph as Tensor("ExpandDims_1:0", shape=(1,), dtype=int32).

In [101]:
# Loss Function

loss = tf.reduce_sum(tf.square(Y_pred-Y))

#Optimizer

optimizer = tf.train.AdamOptimizer(learning_rate)
train = optimizer.minimize(loss)

# RMSE

targets = tf.placeholder(tf.float32, [None, 1])
predictions = tf.placeholder(tf.float32, [None, 1])
rmse = tf.sqrt(tf.reduce_mean(tf.square(targets-predictions)))


ValueError: Tensor("Const:0", shape=(3,), dtype=int32) must be from the same graph as Tensor("Square_4:0", shape=(?, 12, 60), dtype=float32).

In [ ]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    
    #Training Steps
    
    for i in range(iterations):
        _,step_loss = sess.run([train,loss], feed_dict={X: trainX, Y:trainY})
        print("[Step: {}] loss: {}".format(i, step_loss))
        
    test_predict = sess.run(Y_pred, feed_dict={X: testX})
    rmse_val = sess.run(rmse, feed_dict={targets: testY, predictions: test_predict})
    print("RMSE: {}".format(rmse_val))
    